


C_TASK_SRC = C/tasks/src/
C_TASK_BIN = C/tasks/bin/
C_EXTS_SRC = C/exts/src/
C_EXTS_BIN = C/exts/bin/

clltest: $(C_TASK_SRC)clltest.c
	
	gcc -o $(C_TASK_BIN)clltest $(C_TASK_SRC)clltest.c $(C_TASK_SRC)Linkedlist.c
	./$(C_TASK_BIN)clltest
