


C_TASK_SRC = C/tasks/src/
C_TASK_BIN = C/tasks/bin/
C_EXTS_SRC = C/exts/src/
C_EXTS_BIN = C/exts/bin/



memAllocA-1: $(C_TASK_SRC)memAllocA-1.c
	
	gcc -o $(C_TASK_BIN)memAllocA-1 $(C_TASK_SRC)memAllocA-1.c $(C_TASK_SRC)class_timing.c
	./$(C_TASK_BIN)memAllocA-1


memAllocA-2: $(C_TASK_SRC)memAllocA-2.c

	gcc -o $(C_TASK_BIN)memAllocA-2 $(C_TASK_SRC)memAllocA-2.c $(C_TASK_SRC)class_timing.c
	./$(C_TASK_BIN)memAllocA-2

memAllocB: $(C_TASK_SRC)memAllocB.c
	
	gcc -o $(C_TASK_BIN)memAllocB $(C_TASK_SRC)memAllocB.c $(C_TASK_SRC)class_timing.c
	./$(C_TASK_BIN)memAllocB


memAllocB-2: $(C_TASK_SRC)memAllocB-2.c

	gcc -o $(C_TASK_BIN)memAllocB-2 $(C_TASK_SRC)memAllocB-2.c $(C_TASK_SRC)class_timing.c
	./$(C_TASK_BIN)memAllocB-2